const demoDataArray = [
    {
      enrollmentId: "EN987654321",
      surName: "Patel",
      firstName: "Ravi",
      middleName: "Raj",
      mobileNo: "9123456789",
      email: "ravi.patel@example.com",
      password: "securepass",
      gender: "Male",
      dateOfBirth: "1996-11-21",
      program: "UG",
      degree: "BBA",
      degreeName: "Bachelor of Business Administration",
      currentSem: 6,
      currentYear: 3,
      createAt: "2025-02-08T17:45",
    },
    {
      enrollmentId: "EN456789123",
      surName: "Desai",
      firstName: "Priya",
      middleName: "Anand",
      mobileNo: "9988776655",
      email: "priya.desai@example.com",
      password: "mypassword",
      gender: "Female",
      dateOfBirth: "1997-02-05",
      program: "PG",
      degree: "MSc",
      degreeName: "Master of Science",
      currentSem: 2,
      currentYear: 1,
      createAt: "2025-02-08T17:50",
    },
    {
      enrollmentId: "EN321654987",
      surName: "Mehta",
      firstName: "Ayesha",
      middleName: "Kiran",
      mobileNo: "9871234560",
      email: "ayesha.mehta@example.com",
      password: "pass1234",
      gender: "Female",
      dateOfBirth: "1998-08-12",
      program: "UG",
      degree: "BCom",
      degreeName: "Bachelor of Commerce",
      currentSem: 4,
      currentYear: 2,
      createAt: "2025-02-08T17:55",
    },
    {
      enrollmentId: "EN654987321",
      surName: "Thakur",
      firstName: "Karan",
      middleName: "Singh",
      mobileNo: "9765432109",
      email: "karan.thakur@example.com",
      password: "karanpass",
      gender: "Male",
      dateOfBirth: "1999-01-16",
      program: "PG",
      degree: "MBA",
      degreeName: "Master of Business Administration",
      currentSem: 3,
      currentYear: 2,
      createAt: "2025-02-08T18:00",
    },
  ];
  
  export default demoDataArray;
  
  